export const instructors = [
  {
    name: "Sarah J.",
    title: "Yoga & Meditation Instructor",
    image: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor1.jpg",
    detailImage: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor1_detail.jpg",
    experience: "8+ Years",
    skills: ["Vinyasa Yoga", "Meditation", "Mindfulness Coaching", "Breathwork"],
    certifications: ["Certified Yoga Instructor", "Mindfulness Trainer"],
    bio: "Sarah J. is a certified yoga and meditation instructor with over 8 years of experience in helping people find peace, balance, and wellness through yoga and mindfulness practices.",
    about: "Sarah brings a calm, positive, and nurturing approach to her teaching, specializing in Vinyasa flow, meditation, and mindfulness coaching. She believes in creating a welcoming environment where students can explore and deepen their practice at their own pace. Sarah has attended numerous yoga and mindfulness workshops and holds certifications as a yoga instructor and mindfulness trainer. Outside of teaching, she enjoys hiking, traveling, and practicing meditation herself.",
  },
  {
    name: "Rahul V.",
    title: "Yoga Instructor",
    image: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor2.jpg",
    detailImage: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor2_detail.jpg",
    experience: "10+ Years",
    skills: ["Hatha Yoga", "Pranayama", "Yoga Therapy"],
    certifications: ["Certified Yoga Therapist", "Advanced Yoga Trainer"],
    bio: "Rahul V. is an experienced yoga instructor specializing in Hatha yoga and yoga therapy, with a passion for holistic wellness.",
    about: "Rahul's classes focus on alignment, breath, and therapeutic yoga practices. He has worked with diverse groups, helping individuals recover from injuries and improve their overall health. Rahul is committed to making yoga accessible to everyone and continues to study advanced yoga techniques. He enjoys reading, music, and volunteering.",
  },
  {
    name: "Alex K.",
    title: "Yoga & Meditation Instructor",
    image: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor3.jpg",
    detailImage: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor3_detail.jpg",
    experience: "8+ Years",
    skills: ["Vinyasa Yoga", "Meditation", "Mindfulness Coaching", "Breathwork"],
    certifications: ["Certified Yoga Instructor", "Mindfulness Trainer"],
    bio: "Alex K. is a certified yoga and meditation instructor with over 8 years of experience in helping people find peace, balance, and wellness through yoga and mindfulness practices.",
    about: "Alex K. brings a calm, positive, and nurturing approach to her teaching, specializing in Vinyasa flow, meditation, and mindfulness coaching. She believes in creating a welcoming environment where students can explore and deepen their practice at their own pace. Alex has attended numerous yoga and mindfulness workshops and holds certifications as a yoga instructor and mindfulness trainer. Outside of teaching, she enjoys hiking, traveling, and practicing meditation herself.",
  },
  {
    name: "Maya P.",
    title: "Meditation & Mantra Specialist",
    image: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor4.jpg",
    detailImage: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor4_detail.jpg",
    experience: "7+ Years",
    skills: ["Mantra Meditation", "Sound Healing", "Guided Meditation"],
    certifications: ["Certified Meditation Coach", "Sound Healing Practitioner"],
    bio: "Maya P. is a meditation and mantra specialist with a deep understanding of sound healing and guided meditation techniques.",
    about: "Maya's sessions are known for their soothing and transformative effects. She integrates sound healing and mantra meditation to help participants achieve deep relaxation and inner peace. Maya regularly leads workshops and retreats, and enjoys art, music, and nature walks.",
  },
  {
    name: "Anil R.",
    title: "Yoga, Mantra & Meditation Instructor",
    image: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor5.jpg",
    detailImage: process.env.NEXT_PUBLIC_API_BASE_URL + "/uploads/images/instructor5_detail.jpg",
    experience: "12+ Years",
    skills: ["Yoga", "Mantra", "Meditation", "Pranayama"],
    certifications: ["Senior Yoga Instructor", "Mantra Specialist"],
    bio: "Anil R. is a senior yoga, mantra, and meditation instructor with over 12 years of experience in teaching and guiding students.",
    about: "Anil's teaching style blends traditional yoga, mantra chanting, and meditation. He is passionate about helping students discover their inner strength and tranquility. Anil has led many retreats and teacher training programs. He enjoys gardening, mantra, and community service.",
  },
];
