// backend route paths

export const API= {
    AUTH:{
        REGISTER:"/api/auth/register",
        LOGIN :"/api/auth/login",
        FORGOT_PASSWORD: "/api/auth/forgot-password",
        RESET_PASSWORD: "/api/auth/reset-password",
        UPDATE_PROFILE: (id: string) => `/api/auth/${id}`,
        GET_PROFILE: "/api/auth/profile",
        UPDATE_PROFILE_PICTURE: "/api/auth/update-profile",
        DELETE_PROFILE_PICTURE: "/api/auth/profile/picture",
    },
    ADMIN: {
        USERS: "/api/admin/users",
        USER_BY_ID: (id: string) => `/api/admin/users/${id}`,
        CREATE_USER: "/api/admin/users",
        UPDATE_USER: (id: string) => `/api/admin/users/${id}`,
        DELETE_USER: (id: string) => `/api/admin/users/${id}`,
        GET_PROFILE: "/api/admin/profile",
        UPDATE_PROFILE: "/api/admin/profile",
        DELETE_PROFILE_PICTURE: "/api/admin/profile/picture",
        ANNOUNCEMENTS: "/api/admin/announcements",
        ANNOUNCEMENT_BY_ID: (id: string) => `/api/admin/announcements/${id}`,
        PUBLISH_ANNOUNCEMENT: (id: string) => `/api/admin/announcements/${id}/publish`,
    },
    HOME: {
        ROOT: "/api/v1/home",
        MOOD_CHECKINS: "/api/v1/home/mood-checkins",
    },
    MEDITATIONS: {
        LIST: "/api/v1/meditations",
        BY_ID: (id: string) => `/api/v1/meditations/${id}`,
        REVIEWS: (id: string) => `/api/v1/meditations/${id}/reviews`,
    },
    YOGAS: {
        LIST: "/api/v1/yogas",
        BY_ID: (id: string) => `/api/v1/yogas/${id}`,
        REVIEWS: (id: string) => `/api/v1/yogas/${id}/reviews`,
    },
    MANTRAS: {
        LIST: "/api/v1/mantras",
        BY_ID: (id: string) => `/api/v1/mantras/${id}`,
        REVIEWS: (id: string) => `/api/v1/mantras/${id}/reviews`,
    },
    LIBRARY: {
        LIST: "/api/v1/library-items",
        BY_ID: (id: string) => `/api/v1/library-items/${id}`,
        REVIEWS: (id: string) => `/api/v1/library-items/${id}/reviews`,
    },
    ME: {
        SAVED_MEDITATIONS: "/api/v1/me/saved-meditations",
        SAVED_YOGAS: "/api/v1/me/saved-yogas",
        SAVED_MANTRAS: "/api/v1/me/saved-mantras",
        SAVED_LIBRARY: "/api/v1/me/saved-library",
        SAVED_SESSIONS: "/api/v1/me/saved-sessions",
        MEDITATION_PROGRESS: "/api/v1/me/meditation-progress",
        YOGA_PROGRESS: "/api/v1/me/yoga-progress",
        MANTRA_PROGRESS: "/api/v1/me/mantra-progress",
        LIBRARY_PROGRESS: "/api/v1/me/library-progress",
    },
    DASHBOARD: {
        STATS: "/api/dashboard/stats",
        MOOD_CHECKIN: "/api/dashboard/mood-checkin",
        MOOD_CHECKINS: "/api/dashboard/mood-checkins",
        MOOD_SUMMARY: "/api/dashboard/mood-summary",
        RECOMMENDATIONS: "/api/dashboard/recommendations",
        TRENDING: "/api/dashboard/trending",
        RECENT_ACTIVITY: "/api/dashboard/recent-activity",
    },
    PUBLIC: {
        ANNOUNCEMENTS: "/api/admin/announcements/public/list",
    },
    SEARCH: {
        CONTENT: "/api/search/content",
        TRENDING: "/api/search/trending",
        FEATURED: "/api/search/featured",
        BY_GOAL: "/api/search/by-goal",
        SUGGESTIONS: "/api/search/suggestions",
        FILTERS: "/api/search/filters",
    },
    SETTINGS: {
        GET: "/api/me/settings",
        UPDATE: "/api/me/settings",
        GENERAL: "/api/me/settings/general",
        PRIVACY: "/api/me/settings/privacy",
        NOTIFICATIONS: "/api/me/settings/notifications",
        APPEARANCE: "/api/me/settings/appearance",
        DATA: "/api/me/settings/data",
    },
    BOOKINGS: {
        LIST: "/api/v1/bookings",
        BY_ID: (id: string) => `/api/v1/bookings/${id}`,
        CREATE: "/api/v1/bookings",
        UPDATE_STATUS: (id: string) => `/api/v1/bookings/${id}/status`,
        CANCEL: (id: string) => `/api/v1/bookings/${id}/cancel`,
        DELETE: (id: string) => `/api/v1/bookings/${id}`,
    }
}
